config = {'batch_size': 4096,
 'concat_features_across_scales': True,
 'contract': False,
 'data_dirs': ['data/dynerf/flame_steak'],
 'data_downsample': 2,
 'density_activation': 'trunc_exp',
 'depth_tv_weight': 0,
 'device': 'cuda:0',
 'distortion_loss_weight': 0.001,
 'expname': 'flame_steak_ndc_f16_90k_ts1e-3_tspn1e-5_ptv2e-4_ptvpn2e-4_l1ap1e-4_l1appn1e-4_dl1e-3_v4bbox_150tdensity_150t-8d_coo+0.5',
 'grid_config': [{'grid_dimensions': 2,
                  'input_coordinate_dim': 4,
                  'output_coordinate_dim': 16,
                  'resolution': [64, 64, 64, 150]}],
 'histogram_loss_weight': 1.0,
 'isg': False,
 'isg_step': -1,
 'ist_step': 50000,
 'keyframes': False,
 'l1_appearance_planes': 0.0001,
 'l1_appearance_planes_proposal_net': 0.0001,
 'linear_decoder': False,
 'logdir': './logs/flame_salmon',
 'lr': 0.01,
 'max_test_cameras': None,
 'max_test_tsteps': None,
 'max_train_cameras': None,
 'max_train_tsteps': None,
 'multiscale_res': [1, 2, 4, 8],
 'ndc': True,
 'ndc_far': 2.6,
 'near_scaling': 0.95,
 'num_batches_per_dset': 1,
 'num_proposal_iterations': 2,
 'num_proposal_samples': [256, 128],
 'num_samples': 48,
 'num_steps': 90001,
 'optim_type': 'adam',
 'plane_tv_weight': 0.0002,
 'plane_tv_weight_proposal_net': 0.0002,
 'proposal_net_args_list': [{'num_input_coords': 4,
                             'num_output_coords': 8,
                             'resolution': [128, 128, 128, 150]},
                            {'num_input_coords': 4,
                             'num_output_coords': 8,
                             'resolution': [256, 256, 256, 150]}],
 'save_every': 30000,
 'save_outputs': True,
 'scene_bbox': [[-3.0, -1.8, -1.2], [3.0, 1.8, 1.2]],
 'scheduler_type': 'warmup_cosine',
 'single_jitter': False,
 'time_smoothness_weight': 0.001,
 'time_smoothness_weight_proposal_net': 1e-05,
 'train_fp16': True,
 'use_same_proposal_network': False,
 'valid_every': 30000}
